# Pandas

Pandas is an open source, BSD-licensed library providing high-performance, easy-to-use data struucture and data analysis tools.

In [1]:
import pandas as pd
import numpy as np

## Data Frame

In [2]:
mat = np.arange(0, 20).reshape(5, 4)

df = pd.DataFrame(
    data=mat, 
    index=['row%d'%i for i in range(5)],
    columns=['col%d'%i for i in range(4)],
    dtype=float
)
df.head()

      col0  col1  col2  col3
row0   0.0   1.0   2.0   3.0
row1   4.0   5.0   6.0   7.0
row2   8.0   9.0  10.0  11.0
row3  12.0  13.0  14.0  15.0
row4  16.0  17.0  18.0  19.0

Save data frame in a csv file

In [3]:
df.to_csv('files/df.csv')

### Accessing elements in a Data Frame

1) loc - location (row name)
2) iloc - index location
3) column name

In [4]:
df.loc['row1']

col0    4.0
col1    5.0
col2    6.0
col3    7.0
Name: row1, dtype: float64

In [5]:
type(df.loc['row1'])

pandas.core.series.Series

In [6]:
df.iloc[2]

col0     8.0
col1     9.0
col2    10.0
col3    11.0
Name: row2, dtype: float64

In [7]:
type(df.iloc[2])

pandas.core.series.Series

In [8]:
df.iloc[0:3, 0:2]

      col0  col1
row0   0.0   1.0
row1   4.0   5.0
row2   8.0   9.0

In [9]:
print(type(df.iloc[2, 0:2]))
print(type(df.iloc[2:3, 0:2]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [10]:
df['col0']

row0     0.0
row1     4.0
row2     8.0
row3    12.0
row4    16.0
Name: col0, dtype: float64

In [11]:
df[['col1', 'col3']]

      col1  col3
row0   1.0   3.0
row1   5.0   7.0
row2   9.0  11.0
row3  13.0  15.0
row4  17.0  19.0

In [12]:
type(df[['col1', 'col3']])

pandas.core.frame.DataFrame

## Common Operations 

Convert data frame into array

In [13]:
df[['col1', 'col3']]

      col1  col3
row0   1.0   3.0
row1   5.0   7.0
row2   9.0  11.0
row3  13.0  15.0
row4  17.0  19.0

In [14]:
df.iloc[:,1:].values

array([[ 1.,  2.,  3.],
       [ 5.,  6.,  7.],
       [ 9., 10., 11.],
       [13., 14., 15.],
       [17., 18., 19.]])

### isnull()

In [15]:
df.isnull()

       col0   col1   col2   col3
row0  False  False  False  False
row1  False  False  False  False
row2  False  False  False  False
row3  False  False  False  False
row4  False  False  False  False

In [16]:
df.isnull().sum()

col0    0
col1    0
col2    0
col3    0
dtype: int64

### value_counts()

In [17]:
df['col1'].value_counts()

col1
1.0     1
5.0     1
9.0     1
13.0    1
17.0    1
Name: count, dtype: int64

### unique()

In [18]:
df['col3'].unique()

array([ 3.,  7., 11., 15., 19.])

## Accessing CSV File

In [19]:
df = pd.read_csv('files/mercedesbenz.csv')
df.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB

In [21]:
df.describe()

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [22]:
# get unique category count of column X0
df['X0'].value_counts()

X0
z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
ai     34
m      34
e      32
ba     27
at     25
a      21
ax     19
aq     18
i      18
am     18
u      17
aw     16
l      16
ad     14
k      11
au     11
b      11
r      10
as     10
bc      6
ao      4
c       3
q       2
aa      2
ac      1
g       1
ab      1
Name: count, dtype: int64

In [23]:
# Filtering rows by conditioning
df[df['y'] > 100]

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
6,24,128.76,al,r,e,f,d,f,h,s,...,0,0,0,0,0,0,0,0,0,0
8,27,108.67,w,s,as,e,d,f,i,h,...,1,0,0,0,0,0,0,0,0,0
9,30,126.99,j,b,aq,c,d,f,a,e,...,0,0,1,0,0,0,0,0,0,0
10,31,102.09,h,r,r,f,d,f,h,p,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4202,8402,123.34,ap,l,s,c,d,aa,d,r,...,0,0,0,0,0,0,0,0,0,0
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

In [24]:
test_df = pd.read_csv('files/test.csv', sep='#')
test_df.head()

  Unnamed: 0  col0  col1  col2  col3
0       row0   0.0   1.0   2.0   3.0
1       row1   4.0   5.0   6.0   7.0
2       row2   8.0   9.0  10.0  11.0
3       row3  12.0  13.0  14.0  15.0
4       row4  16.0  17.0  18.0  19.0

In [25]:
test_df = pd.read_csv('files/test.csv', sep='#', index_col=0)
test_df.head()

      col0  col1  col2  col3
row0   0.0   1.0   2.0   3.0
row1   4.0   5.0   6.0   7.0
row2   8.0   9.0  10.0  11.0
row3  12.0  13.0  14.0  15.0
row4  16.0  17.0  18.0  19.0

In [26]:
test_df = pd.read_csv('files/test.csv', sep='#', usecols=['col0', 'col2'])
test_df.head()

   col0  col2
0   0.0   2.0
1   4.0   6.0
2   8.0  10.0
3  12.0  14.0
4  16.0  18.0

In [27]:
data = ('a,b,c,d\n'
'1,2,3,4\n'
'5,6,7,8\n'
'9,10,11\n')
print(data)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11

In [28]:
from io import StringIO
df = pd.read_csv(StringIO(data), dtype={'a': int, 'b': float, 'c': int, 'd':str})
df.head()

   a     b   c    d
0  1   2.0   3    4
1  5   6.0   7    8
2  9  10.0  11  NaN

In [29]:
df.dtypes

a      int64
b    float64
c      int64
d     object
dtype: object

In [30]:
data = (
    'a,b,c\n'
    '4,Apple,Bat,\n'
    '8,Orange,Cow,'
)
df = pd.read_csv(StringIO(data))
df.head()

        a    b   c
4   Apple  Bat NaN
8  Orange  Cow NaN

In [31]:
df = pd.read_csv(StringIO(data), index_col=False, usecols=['a','c'])
df.head()

   a    c
0  4  Bat
1  8  Cow

In [32]:
data = (
    'a,b\n'
    'abra\\,cadabra\\,5'
)
df = pd.read_csv(StringIO(data), escapechar='\\')
df.head()

                a   b
0  abra,cadabra,5 NaN

## Accessing JSON Data

In [45]:
data = '''{
    "name" : "Swarnotaj003",
    "email" : "swarnotajk@gmail.com",
    "job" : {
        "title1" : "AI Engineer",
        "title2" : "Software Developer"
    }
}'''
df = pd.read_json(data)
df.head()

C:\Users\SWARNOTAJ\AppData\Local\Temp\ipykernel_17516\3447115450.py:9: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(data)

                name                 email                 job
title1  Swarnotaj003  swarnotajk@gmail.com         AI Engineer
title2  Swarnotaj003  swarnotajk@gmail.com  Software Developer

In [46]:
df.to_json()

'{"name":{"title1":"Swarnotaj003","title2":"Swarnotaj003"},"email":{"title1":"swarnotajk@gmail.com","title2":"swarnotajk@gmail.com"},"job":{"title1":"AI Engineer","title2":"Software Developer"}}'

In [47]:
df.to_json(orient='records')

'[{"name":"Swarnotaj003","email":"swarnotajk@gmail.com","job":"AI Engineer"},{"name":"Swarnotaj003","email":"swarnotajk@gmail.com","job":"Software Developer"}]'

### Converting JSON into CSV

In [42]:
# Access JSON data from web
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [43]:
# Save to csv file
df.to_csv('files/wine.csv')

## Accessing HTML data

In [ ]:
df = pd.read_html('https://www.fdic.gov/bank/individual/failed/banklist.html')
type(df)    # returns a list of tables found in the HTML page

list

In [56]:
df[0].head()

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
1,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
2,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
3,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
4,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549

In [ ]:
df = pd.read_html('https://en.wikipedia.org/wiki/Mobile_country_code', match='Country')
# match attribute matches with any table with that column name
df[0].head()

## Accessing Excel Files

In [61]:
df_excel = pd.read_excel('files/Excel.xlsx')
df_excel

    a   b   c   d
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

## Pickling

All Pandas objects are equipped with to_pickle() methods which use Python's cPickle module to save data structures to disk using the pickle format.

In [62]:
df_excel.to_pickle('files/df_excel')

In [63]:
df = pd.read_pickle('files/df_excel')
df

    a   b   c   d
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16